project:
  name: zephyr-rtos-test
  type: zephyr
  buildType: ci

environment:
  agent: "linux docker x86_64"
  timeout: 30
  docker:
    image: zephyr-builder:latest
    args: "-v /mnt/workspace/zephyr:/mnt/workspace/zephyr"

zephyr:
  sdkPath: /opt/zephyr-sdk-0.16.8
  westWorkspace: /mnt/workspace/zephyr
  board: rpi_4b/bcm2711
  app: samples/hello_world
  pristine: true

stages:
  - checkout
  - build
  - notify
